#!/bin/bash
sudo apt install git kakoune tmux -y

git config --global user.name "Andreas Stocker"
git config --global user.email "stoand@proton.me"
git config --global core.editor "kak"

rm ~/.ssh -r
cp /var/.ssh ~/.ssh -r
chmod -R 700 ~/.ssh

# Merge home folder into user home
 
(cd home && rsync -a . ~/)

source ~/.bashrc

git clone https://github.com/junegunn/fzf ~/.fzf
~/.fzf/install --all

git clone https://github.com/h-youhei/kakoune-surround ~/.kakoune-surround

(cd /tmp/ && git clone https://github.com/nordtheme/xfce-terminal && cd xfce-terminal && ./install.sh)

mkdir -p ~/.local/bin

# Download Kakoune Language Server

(cd /tmp &&
    wget https://github.com/kakoune-lsp/kakoune-lsp/releases/download/v15.0.1/kak-lsp-v15.0.1-x86_64-unknown-linux-musl.tar.gz &&
    tar xzvf kak-lsp-v15.0.1-x86_64-unknown-linux-musl.tar.gz &&
    mv kak-lsp ~/.local/bin/)

# Download Zig

(cd /tmp/ && wget https://ziglang.org/builds/zig-linux-x86_64-0.12.0-dev.2805+79e99c401.tar.xz &&
    tar -xf zig-linux-x86_64-0.12.0-dev.2805+79e99c401.tar.xz && mv zig-linux-x86_64-0.12.0-dev.2805+79e99c401 ~/.zig)

(cd /tmp/ && git clone https://github.com/zigtools/zls && cd zls && zig build && cp zig-out/bin/zls ~/.local/bin)
