#!/bin/bash
sudo apt install git kakoune tmux -y

git config --global user.name "Andreas Stocker"
git config --global user.email "stoand@proton.me"

sudo rm ~/.ssh -r
sudo cp /var/.ssh ~/.ssh -r
sudo chmod -R 777 ~/.ssh
 
rsync -abviuzP home/ ~/

git clone https://github.com/junegunn/fzf ~/.fzf
~/.fzf/install --all

git clone https://github.com/h-youhei/kakoune-surround ~/.kakoune-surround

(cd /tmp/ && git clone https://github.com/nordtheme/xfce-terminal && cd xfce-terminal && ./install.sh)

mkdir -p ~/.local/bin

cd /tmp
wget https://github.com/kakoune-lsp/kakoune-lsp/releases/download/v15.0.1/kak-lsp-v15.0.1-x86_64-unknown-linux-musl.tar.gz
tar xzvf kak-lsp-v15.0.1-x86_64-unknown-linux-musl.tar.gz
mv kak-lsp ~/.local/bin/
