#!/usr/bin/env bash

cd "$(dirname "${BASH_SOURCE[0]}")"

sudo apt install -y git curl rsync wget kakoune tmux cmake pkg-config libfreetype6-dev libfontconfig1-dev libxcb-xfixes0-dev libxkbcommon-dev python3

git config --global user.name "Andreas Stocker"
git config --global user.email "stoand@proton.me"
git config --global core.editor "kak"
git config --global init.defaultBranch "main"

# Merge home folder into user home
 
(cd home && rsync -a . ~/)

# Has no effect
# source ~/.bashrc

git clone https://github.com/junegunn/fzf ~/.fzf
~/.fzf/install --all

git clone https://github.com/h-youhei/kakoune-surround ~/.kakoune-surround

mkdir -p ~/.local/bin

# Install Rust

curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
. "$HOME/.cargo/env"

# Install Alacritty

cargo install alacritty


# Download Alacritty Themes

mkdir -p ~/.config/alacritty/themes
git clone https://github.com/alacritty/alacritty-theme ~/.config/alacritty/themes

# Download Kakoune Language Server

(cd /tmp &&
    wget https://github.com/kakoune-lsp/kakoune-lsp/releases/download/v15.0.1/kak-lsp-v15.0.1-x86_64-unknown-linux-musl.tar.gz &&
    tar xzvf kak-lsp-v15.0.1-x86_64-unknown-linux-musl.tar.gz &&
    mv kak-lsp ~/.local/bin/)

# Download Zig and Zig language server

(cd /tmp/ && wget https://ziglang.org/builds/zig-linux-x86_64-0.12.0-dev.2805+79e99c401.tar.xz &&
    tar -xf zig-linux-x86_64-0.12.0-dev.2805+79e99c401.tar.xz && mv zig-linux-x86_64-0.12.0-dev.2805+79e99c401 ~/.zig)

(cd /tmp/ && git clone https://github.com/zigtools/zls && cd zls && ~/.zig/zig build && cp zig-out/bin/zls ~/.local/bin)

cd

~/.cargo/bin/alacritty -e tmux new-session \; send-keys 'kak' C-m \; split-window -h \; resize-pane -R 20 \; last-pane \; & disown

sleep 3 && kill -9 $PPID
